name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2.5.0

      - name: Install pnpm Package Manager
        uses: pnpm/action-setup@v2.2.4

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test
